all:problem_a.out problem_b.out problem_c.out

problem_a.out:problem_a.c
	gcc problem_a.c -Wall -Werror -o problem_a.out

problem_b.out:problem_b.c
	gcc problem_b.c -Wall -Werror -o problem_b.out

problem_c.out:problem_c.c
	gcc problem_c.c -Wall -Werror -o problem_c.out

clean:
	rm -rfv *.out *.o
